AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  DBname:
    Type: String
    Default: "Registration"
    Description: Database name
  DynamoTableName:
    Type: String
    Default: "EventLogs"
    Description: DynamoDB table name
  DBUsername:
    Type: String
    Default: "admin"
    NoEcho: true
    Description: Database admin username
  DBPassword:
    Type: String
    NoEcho: true
    Description: Database admin password

Resources:
  RDSInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      DBInstanceClass: db.t4g.micro
      AllocatedStorage: 20
      Engine: mysql
      EngineVersion: 8.0.39
      MasterUsername: !Ref DBUsername
      MasterUserPassword: !Ref DBPassword
      PubliclyAccessible: false
      DeletionProtection: false
      StorageEncrypted: false
      DBInstanceIdentifier: finaktiva-db
      DBName: !Ref DBname
  
  DBSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: DBCredentials
      Description: "Credentials for the DB"
      SecretString: 
        !Sub '{"username": "${DBUsername}", "password": "${DBPassword}"}'

  DynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Ref DynamoTableName
      AttributeDefinitions:
        - AttributeName: "date"
          AttributeType: "S"
        - AttributeName: "type"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "date"
          KeyType: "HASH"
        - AttributeName: "type"
          KeyType: "RANGE"
      BillingMode: PAY_PER_REQUEST

Outputs:
  DBSecretArn:
    Description: "DB Secret ARN"
    Value: !Ref DBSecret
    Export:
      Name: DBSecretArn 

  RDSInstanceArn:
    Description: "RDS Instance ARN"
    Value: !Sub arn:aws:rds:${AWS::Region}:${AWS::AccountId}:db/${RDSInstance}
    Export:
      Name: RDSInstanceArn

  DynamoDBTableName:
    Description: Name of the DynamoDB table
    Value: !Ref DynamoDBTable
    Export:
      Name: DynamoDBTableName

  DynamoDBTableArn:
    Description: ARN of the DynamoDB table
    Value: !GetAtt DynamoDBTable.Arn
    Export:
      Name: DynamoDBTableArn
