AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  DBUsername:
    Type: String
    Default: "admin"
    NoEcho: true
    Description: Database admin username
  DBPassword:
    Type: String
    NoEcho: true
    Description: Database admin password

Resources:
  # Aurora MySQL DB Instance (standalone)
  AuroraDBInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      DBInstanceClass: db.t3.micro
      Engine: mysql
      EngineVersion: "5.7"
      DBInstanceIdentifier: MyAuroraInstance
      MasterUsername: !Ref DBUsername
      MasterUserPassword: !Ref DBPassword
      AllocatedStorage: "5"
      PubliclyAccessible: false
      DBName: Registration

  # Secrets Manager for Aurora DB credentials
  AuroraDBSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: AuroraDBCredentials
      Description: "Credentials for Aurora DB"
      SecretString: 
        !Sub '{"username": "${DBUsername}", "password": "${DBPassword}"}'

  # DynamoDB Table for EventLogs
  DynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: EventLogs
      AttributeDefinitions:
        - AttributeName: "date"
          AttributeType: "S"
        - AttributeName: "type"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "date"
          KeyType: "HASH"
        - AttributeName: "type"
          KeyType: "RANGE"
      BillingMode: PAY_PER_REQUEST

Outputs:
  AuroraDBSecretArn:
    Description: "Aurora DB Secret ARN"
    Value: !Ref AuroraDBSecret
    Export:
      Name: AuroraDBSecretArn 

  AuroraDBInstanceEndpoint:
    Description: "Aurora DB Instance Endpoint"
    Value: !GetAtt AuroraDBInstance.Endpoint.Address

  DynamoDBTableName:
    Description: "DynamoDB Table Name"
    Value: !Ref DynamoDBTable
    Export:
      Name: DynamoDBTableName
